In [11]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv" #reading the file
df = pd.read_csv(url,index_col=0)
df.head()

Status   Brand       Model  \
Laptop                                                                          
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...    New    Asus  ExpertBook   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...    New  Alurin          Go   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...    New    Asus  ExpertBook   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...    New     MSI      Katana   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...    New      HP         15S   

                                                              CPU  RAM  \
Laptop                                                                   
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...  Intel Core i5    8   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...  Intel Celeron    8   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...  Intel Core i3    8   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...  Intel Core i7   16   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...  Intel Core i5   16   

                                                    Storage Storage type  \
Laptop                                                                     
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...      512          SSD   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...      256          SSD   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...      256          SSD   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...     1000          SSD   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...      512          SSD   

                                                         GPU  Screen Touch  \
Laptop                                                                       
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...       NaN    15.6    No   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...       NaN    15.6    No   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...       NaN    15.6    No   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...  RTX 3050    15.6    No   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...       NaN    15.6    No   

                                                    Final Price  
Laptop                                                           
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...      1009.00  
Alurin Go Start Intel Celeron N4020/8GB/256GB S...       299.00  
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...       789.00  
MSI Katana GF66 12UC-082XES Intel Core i7-12700...      1199.00  
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...       669.01

In [2]:
print(pd.__version__)

2.2.2


In [3]:
records=len(df)
print(records)

2160


In [4]:
brands=df.Brand
brands=brands.unique()
print(len(brands))

27


In [5]:
(df.isnull().sum()>0).sum()

3

In [6]:
df[df['Brand']=="Dell"]["Final Price"].max()

3936.0

In [7]:
dfmedian=df.Screen.median()
print(dfmedian)

15.6


In [8]:
df_frequent=df.Screen.mode()
df.Screen.fillna(df_frequent)
print(df.Screen.median())

15.6


In [9]:
X=df[df["Brand"]=="Innjoo"][['RAM','Storage','Screen']].values

In [10]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [14]:
XTX=np.dot(X.T,X) 
XTXinv=np.linalg.inv(XTX)
y = [1100, 1300, 800, 900, 1000, 1100]
val=np.dot(XTXinv,X.T)
w=np.dot(val,y)
print(sum(w))

91.2998806299555
